name: art_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  hive_generator: ^2.0.1
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gossip_girl_1.webp
    - assets/images/gossip_girl_2.webp
    - assets/images/gossip_girl_4.webp
    - assets/images/gossip_girl_5.webp
    - assets/images/female_artists_1.png
    - assets/images/female_artists_2.png
    - assets/images/female_artists_3.png
    - assets/images/female_artists_4.png
    - assets/images/female_artists_5.png
    - assets/images/female_artists_6.png
    - assets/images/female_artists_7.png
    - assets/images/female_artists_8.png
    - assets/images/female_artists_9.png
    - assets/images/female_artists_10.png
    - assets/images/exhibition1.jpg
    - assets/images/exhibition2.jpg
    - assets/images/exhibition3.jpg
    - assets/images/exhibition4.jpg
    - assets/images/ateneum1.webp
    - assets/images/kiasma1.webp
    - assets/images/EMMA1.jpg
    - assets/images/luonnontieteellinen1.jpg